package com.esgi.nova.core.domain.users.exceptions

class UserAlreadyExistsException(username: String) : Throwable() {

}