package com.esgi.nova.application.services.users.exceptions

class UserNotFoundByIdException : Throwable() {

}
